language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

services:
  - mysql

install:
  - "pip install -U setuptools"
  - "pip install ."

script:
  - export PYTHONPATH=.:vendor
  - export TEST_CONFIG=tests/config/travis.json
  - python -m unittest discover tests
