language: python
python:
- 3.9
services:
- mysql
install:
- mysql -uroot -hlocalhost -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';FLUSH
  PRIVILEGES;"
- pip install .
script:
- export PYTHONPATH=.:vendor
- export TEST_CONFIG=tests/resources/config/travis.json
- python -m unittest discover tests
